//! Emitting 8R's result: the renamed program as dex file(s), plus a ProGuard-format mapping
//! that decompilers (jadx, etc.) can load to show recovered names on the *original* APK.

use std::fmt::Write;

use eightr_ir::model::Program as Model;
use eightr_ir::types::parse_proto;

use crate::error::{Error, Result};
use crate::pipeline::Outcome;

pub struct Output {
    /// (file name, bytes), in multidex order.
    pub dex: Vec<(String, Vec<u8>)>,
    /// `recovered -> current` mapping (ProGuard format: left side is the name to show, right
    /// side is the name in the input).
    pub mapping: String,
}

/// Descriptor → Java type name (`[Ljava/lang/String;` → `java.lang.String[]`).
fn java_type(d: &str) -> String {
    let dims = d.bytes().take_while(|&b| b == b'[').count();
    let base = match &d[dims..] {
        "V" => "void".to_string(),
        "Z" => "boolean".to_string(),
        "B" => "byte".to_string(),
        "S" => "short".to_string(),
        "C" => "char".to_string(),
        "I" => "int".to_string(),
        "J" => "long".to_string(),
        "F" => "float".to_string(),
        "D" => "double".to_string(),
        other => other.strip_prefix('L').and_then(|o| o.strip_suffix(';')).unwrap_or(other).replace('/', "."),
    };
    base + &"[]".repeat(dims)
}

/// Writes the program, splitting into more dex files only if index limits require it.
fn write_dexes(model: &Model) -> Result<Vec<Vec<u8>>> {
    let n = model.classes.len();
    let mut files = 1;
    loop {
        // Contiguous chunks of the (descriptor-sorted) class list: deterministic.
        let per = n.div_ceil(files).max(1);
        match eightr_dexwrite::write_split(model, files, |i| (i / per).min(files - 1)) {
            Ok(v) => return Ok(v),
            Err(e) if e.0.contains("16 bits") && files < n.max(1) => files += 1,
            Err(e) => return Err(Error::Write(e.0)),
        }
    }
}

pub fn emit(outcome: &Outcome) -> Result<Output> {
    let before = &outcome.program;
    let r = &outcome.renaming;
    let new_class = |d: &str| r.classes.get(d).cloned().unwrap_or_else(|| d.to_string());
    let new_type = |d: &str| {
        let dims = d.bytes().take_while(|&b| b == b'[').count();
        format!("{}{}", &d[..dims], new_class(&d[dims..]))
    };

    // Mapping text, from the pre-rename program.
    let mut mapping = String::from("# Generated by 8R. Left: recovered name. Right: name in the input.\n");
    // The mapping applies to the *input*: classes and members rewrites created (split
    // subclasses, re-boxed enums, 8R's adapters) aren't there.
    let created = |c: &eightr_ir::model::Class, d: &str| {
        d.contains("$$Split") || d.contains("$8r$") || c.methods.iter().any(|m| before.str(m.name).contains("$8r$"))
    };
    for id in before.class_ids() {
        let c = before.class(id);
        let d = before.descriptor(id);
        if created(c, d) {
            continue;
        }
        let mut members = String::new();
        for f in &c.fields {
            let (name, ty) = (before.str(f.name), before.str(f.ty));
            if let Some(new) = r.fields.get(&(d.to_string(), name.to_string(), ty.to_string())) {
                let _ = writeln!(members, "    {} {new} -> {name}", java_type(&new_type(ty)));
            }
        }
        for m in &c.methods {
            let (name, proto) = (before.str(m.name), before.str(m.proto));
            if let Some(new) = r.methods.get(&(d.to_string(), name.to_string(), proto.to_string())) {
                let (params, ret) = parse_proto(proto).expect("valid proto");
                let params: Vec<String> = params.iter().map(|t| java_type(&new_type(t))).collect();
                let _ = writeln!(members, "    {} {new}({}) -> {name}", java_type(&new_type(ret)), params.join(","));
            }
        }
        let renamed = r.classes.contains_key(d);
        if renamed || !members.is_empty() {
            let _ = writeln!(mapping, "{} -> {}:", java_type(&new_class(d)), java_type(d));
            mapping.push_str(&members);
        }
    }

    let mut model = before.model.clone();
    r.apply(&mut model);
    let files = write_dexes(&model)?;
    let dex = files
        .into_iter()
        .enumerate()
        .map(|(i, b)| (if i == 0 { "classes.dex".to_string() } else { format!("classes{}.dex", i + 1) }, b))
        .collect();
    Ok(Output { dex, mapping })
}
